apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: app
build:
  artifacts:
  - image: amitpandia/helloworldapp
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: app
        chartPath: ./helm-chart/app
        valuesFiles:
          - ./helm-chart/app/values.yaml
        artifactOverrides:
          image: amitpandia/helloworldapp

