apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    path: argo-helm-app/charts/app
    repoURL: https://github.com/amit-pandia/helm-experiments.git
    helm:
      releaseName: myapp
      version: v2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
