apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: skaffold-app
build:
  artifacts:
  - image: amitpandia/helloworldapp
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-pod.yaml
